var subs = [
    { name: 'cinzenta', lat: 0.901, lng: -65.698, zoom: 6, pinLat: 0, pinLng: 0, descricao: 'O Pouso da Cinzenta', informacoes: '', informacoes: '' },
    { name: 'saisepedras', lat: 13.923, lng: -69.368, zoom: 6, pinLat: 0, pinLng: 0, descricao: 'Terras de Sais e Pedras', informacoes: '' },
/*    */{ name: 'dosal', lat: 17.613, lng: -66.753, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Terra do Sal', informacoes: '' },
/*    */{ name: 'dapedra', lat: 14.594, lng: -67.094, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Terra da Pedra', informacoes: '' },
/*    */{ name: 'detheus', lat: 9.990, lng: -66.302, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Terra de Theus', informacoes: '' },
    { name: 'maraba', lat: 24.347, lng: -68.643, zoom: 6, pinLat: 0, pinLng: 0, descricao: 'O Braço de Marabá', informacoes: '' },
/*    */{ name: 'dosvelhos', lat: 27.347, lng: -72.015, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'Ilha dos Velhos', informacoes: '' },
/*    */{ name: 'dastrocas', lat: 26.392, lng: -70.214, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'Ilha das Trocas', informacoes: '' },
/*    */{ name: 'dopoder', lat: 28.188, lng: -67.972, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'Ilha do Poder', informacoes: '' },
/*    */{ name: 'dasentenca', lat: 23.584, lng: -75.476, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Terra da Sentença', informacoes: '' },
/*    */{ name: 'dezerai', lat: 23.645, lng: -68.384, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'O Estreito de Zerai', informacoes: '' },
    { name: 'fieldon', lat: 13.966, lng: -45.396, zoom: 6, pinLat: 0, pinLng: 0, descricao: 'As Terras Árduas de Fieldon', informacoes: '' },
    { name: 'zionr', lat: 25.404, lng: -52.976, zoom: 6, pinLat: 0, pinLng: 0, descricao: 'As Terras Árduas de Zionr', informacoes: '' },
    { name: 'matim', lat: 25.443, lng: -37.595, zoom: 6, pinLat: 0, pinLng: 0, descricao: 'As Terras de Matím', informacoes: '' },
/*    */{ name: 'estreito', lat: 29.167, lng: -44.984, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'O Estreito', informacoes: '' },
/*    */{ name: 'dacruz', lat: 28.710, lng: -39.490, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'Terra da Cruz', informacoes: '' },
/*    */{ name: 'zionarrs', lat: 27.868, lng: -33.195, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'Terra dos Zionarrs', informacoes: '' },
/*    */{ name: 'homens1', lat: 23.383, lng: -45.231, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Terra dos Homens (de Matím)', informacoes: '' },
/*    */{ name: 'monstros', lat: 23.614, lng: -36.815, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Terra dos Monstros', informacoes: '' },
    { name: 'confins', lat: 25.125, lng: -26.038, zoom: 6, pinLat: 0, pinLng: 0, descricao: 'Os Confins da Terra', informacoes: '' },
/*    */{ name: 'bruxos', lat: 28.493, lng: -30.207, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'Terra dos Bruxos', informacoes: '' },
/*    */{ name: 'cerco', lat: 21.320, lng: -29.888, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'Domínio Perdido de Cerco', informacoes: '' },
/*    */{ name: 'docaos', lat: 27.010, lng: -24.170, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Floresta do Caos (Terra do Caos)', informacoes: '' },
/*    */{ name: 'gaudur', lat: 21.923, lng: -24.456, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'Floresta de Gaudur (Terra de Gaudur)', informacoes: '' },
    { name: 'sagmatim', lat: 24.607, lng: -17.336, zoom: 6, pinLat: 0, pinLng: 0, descricao: 'As Terras de SagMátim', informacoes: '' },
/*    */{ name: 'docaos2', lat: 27.010, lng: -24.170, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Qa\'os (Terra do Caos)', informacoes: '' },
/*    */{ name: 'daordem', lat: 26.912, lng: -18.556, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Am\'bá (Terra da Ordem)', informacoes: '' },
/*    */{ name: 'gaudur2', lat: 21.923, lng: -24.456, zoom: 8, pinLat: 0, pinLng: 0, descricao: 'Gau\'dur (Terra de Gaudur)', informacoes: '' },
/*    */{ name: 'dalei', lat: 19.969, lng: -17.424, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Ya\'jad (Terra da Lei)', informacoes: '' },
/*    */{ name: 'dajustica', lat: 22.391, lng: -12.612, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Rad\'afan (Terra da Justiça)', informacoes: '' },
/*    */{ name: 'ajaf', lat: 15.390, lng: -17.622, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Aj\'af', informacoes: '' },
    { name: 'niogro', lat: 16.784, lng: -4.504, zoom: 6, pinLat: 0, pinLng: 0, descricao: 'O Deserto de Niogro', informacoes: '' },
    { name: 'mileni', lat: 3.974, lng: -0.198, zoom: 6, pinLat: 0, pinLng: 0, descricao: 'As Terras de Mileni', informacoes: '' },
/*    */{ name: 'dedaeldon', lat: 9.850, lng: -4.109, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Deserto de Daeldon (Deserto de Niogro)', informacoes: '' },
/*    */{ name: 'acropole', lat: 7.297, lng: -3.274, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Campos Acrópole', informacoes: '' },
/*    */{ name: 'propicios', lat: 1.384, lng: -5.779, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Terra dos Propícios', informacoes: '' },
/*        */{ name: 'nieldin', lat: 2.855, lng: -6.037, zoom: 8, pinLat: 2.729, pinLng: -7.982, descricao: 'Nieldin', informacoes: '' },
/*        */{ name: 'nascente', lat: 2.584, lng: -3.724, zoom: 9, pinLat: 2.178, pinLng: -3.323, descricao: 'Nascente', informacoes: '' },
/*        */{ name: 'movilas', lat: 1.521, lng: -5.477, zoom: 8, pinLat: 1.521, pinLng: -5.477, descricao: 'Campos Movilás', informacoes: '' },
/*        */{ name: 'sagmain', lat: 0.879, lng: -7.364, zoom: 9, pinLat: 1.145, pinLng: -7.322, descricao: 'Sagmain', informacoes: '' },
/*        */{ name: 'matamar', lat: -0.225, lng: -5.065, zoom: 8, pinLat: -1.258, pinLng: -5.823, descricao: 'Matamar', informacoes: '' },
/*    */{ name: 'barbados', lat: 1.549, lng: -0.483, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Terra dos Barbados', informacoes: '' },
/*        */{ name: 'divisa', lat: 4.839, lng: -5.120, zoom: 8, pinLat: 4.253, pinLng: -4.164, descricao: 'Divisa', informacoes: '' },
/*        */{ name: 'rincam', lat: 4.062, lng: -0.505, zoom: 8, pinLat: 3.952, pinLng: -0.126, descricao: 'Rincam', informacoes: '' },
/*        */{ name: 'narages', lat: 2.328, lng: -0.582, zoom: 8, pinLat: 1.917, pinLng: 0.198, descricao: 'Narages', informacoes: '' },
/*    */{ name: 'homens2', lat: 0.978, lng: 4.252, zoom: 7, pinLat: 0, pinLng: 0, descricao: 'Terra dos Homens (de Mileni)', informacoes: '' },
/*        */{ name: 'daelda', lat: 3.058, lng: 4.059, zoom: 8, pinLat: 3.629, pinLng: 5.614, descricao: 'Daelda (Nasckos)', informacoes: '' },
/*        */{ name: 'caledoria', lat: 1.143, lng: 4.180, zoom: 8, pinLat: 1.219, pinLng: 3.516, descricao: 'Caledória (Goan)', informacoes: '' },
/*        */{ name: 'minaverde', lat: 0.321, lng: 5.630, zoom: 9, pinLat: 0.437, pinLng: 6.180, descricao: 'Minaverde', informacoes: '' },
/*        */{ name: 'marcamont', lat: -0.555, lng: 4.087, zoom: 8, pinLat: -1.467, pinLng: 4.186, descricao: 'Marcamont', informacoes: '' }
];

function getSubMap(name) {
    return subs.filter(function (obj) {
        return obj.name === name;
    })[0];
}